[package]
name = "linkage"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
palette = "0.5.0"
rand = "0.8"
serde_json = "1.0"
statrs = "0.15.0"

[dependencies.time]
version = "0.2"
features = ["serde", "std"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.iced]
version = "0.3"
features = ["palette"]

[dependencies.iced_native]
version = "0.4"

[dependencies.iced_graphics]
version = "0.2"

[dependencies.iced_futures]
version = "0.3"

[patch.crates-io]
iced = { git = "https://github.com/hecrj/iced.git", rev = "a6dbaf0f5fd3590a8cfe92f924184c5d78e00152"}
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "a6dbaf0f5fd3590a8cfe92f924184c5d78e00152"}
iced_graphics = { git = "https://github.com/hecrj/iced.git", rev = "a6dbaf0f5fd3590a8cfe92f924184c5d78e00152"}
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "a6dbaf0f5fd3590a8cfe92f924184c5d78e00152"}
