[package]
name = "linkage"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
palette = "0.5.0"
rand = "0.8"
serde_json = "1.0"
# Needed to solve an Iced dependency problem...
web-sys = "0.3.50"

[dependencies.time]
version = "0.2"
features = ["serde", "std"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.iced]
version = "0.3"
features = ["palette"]

[dependencies.iced_native]
version = "0.4"

[dependencies.iced_graphics]
version = "0.2"

[dependencies.iced_futures]
version = "0.3"

[patch.crates-io]
iced = { git = "https://github.com/hecrj/iced.git", rev = "e68da229b384fbe78514dab0b13c8eb4637f4f5d"}
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "e68da229b384fbe78514dab0b13c8eb4637f4f5d"}
iced_graphics = { git = "https://github.com/hecrj/iced.git", rev = "e68da229b384fbe78514dab0b13c8eb4637f4f5d"}
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "e68da229b384fbe78514dab0b13c8eb4637f4f5d"}
